### ISSUE TITLE
Able to inherit parent EEs by child EEs?

### ISSUE THREAD

**Issue by shah** [ihack2712/eventemitter#1]
@ihack2712 I love this library, thanks for putting it together! I have a need to subclass emitters (inherit from parent) -- is that possible? Meaning, I have one typed emitter and I'd like to create other typed emitters inheriting from base emitters.

thanks!

**Comment by ihack2712** [comment]
Hi @shah, thank you for the feedback!

When you say subclass inheriting from parent, do you mean for the sub class to bubble events up to the parent, or making new event emitters with the same listeners and events?

**Comment by shah** [comment]
Great question @ihack2712 - I meant "making new event emitters with the same listeners and events". Here's my requirement:

* Class A has two events
* Class B inherits from A's two events and adds a few more
* Class C inherits from B's and gets A's + B's events / listeners / etc.

**Comment by shah** [comment]
Just the types would be a great start @ihack2712 -- if bubbling is possible, that would be fantastic too but if we had types inherited then it means we could "manually" do the bubbling. thanks!

**Comment by ihack2712** [comment]
Okay so the types and listeners shouldn't be hard to add. I assume you just want some `clone` function?

**Comment by shah** [comment]
Great! I don't immediately need a clone function but it would be a terrific addition if it's easy. Here's my current use case -- I'm creating a type-safe "task runner" using your EE that would allow me to define tasks in Deno and run them from the command line. 

See: [core_test.ts](https://github.com/resFactory/factory/blob/main/lib/task/core_test.ts) to see what I'm trying to accomplish (the accompanying [core.ts](https://github.com/resFactory/factory/blob/main/lib/task/core.ts) will be instructive). The idea is to allow the definition of tasks as events and then allow calling them from the command line. Almost like a replacement for `make`, `rake`, and other task runners.

As you can see in the `core_test.ts` synthetic use case, I have a `Tasks` class and if I wanted to re-use the tasks in that class I would need to re-create them.

That's why having just the types inheritance would be great so I can put "common tasks" into one class, and then subclass for others.

**Comment by ihack2712** [comment]
https://deno.land/x/eventemitter@1.2.4/mod.ts#L228 I think this should do the trick, feel free to reopen if something is wrong (this is untested code)

**Comment by shah** [comment]
@ihack2712 great, thanks! Should typesafety be preserved across subclasses or will only the cloning work? I'm not seeing how I can do the subclasses with just the new `clone` method. Could you elaborate?

**Comment by ihack2712** [comment]
![image](https://user-images.githubusercontent.com/35933830/156590536-a5edff74-7f6a-48b6-8762-6ce00ddc8dfd.png)

The clone function preserves the events from the source and clones its listeners. You can avoid cloning listeners by doing `emitter.clone(false)`

**Comment by shah** [comment]
Thanks for the elaboration @ihack2712, the clone is perfect but what I'm trying to do is the following:

![image](https://user-images.githubusercontent.com/47497/156696791-b271e40e-cfc2-43e6-8dfc-31550b8e6bd0.png)

Should the above work or will subclassing not be possible?

**Comment by ihack2712** [comment]
Hello @shah, sorry for taking so long to respond! I will be discontinuing development on this module as I am working on a new and improved module, it will be released under a different name as it differs in its behaviour from an event emitter. I do suggest you use that one instead when it is released.

It will also include the features that you are looking for.

**Comment by ihack2712** [comment]
But to answer your question, this is possible, although must be implemented by yourself.

```ts
import { EventEmitter } from "https://deno.land/x/eventemitter@1.2.4/mod.ts";

// To make Deno lint less irritating.
// deno-lint-ignore no-explicit-any
type Any = any;

type Callback = (...args: Any[]) => Any | Promise<Any>;
type EventsType = { [key: string]: Callback } & { [key: number]: Callback };

// deno-lint-ignore ban-types
class MyExtendableEventEmitter<E extends EventsType = {}>
  extends EventEmitter<E> {
  // deno-lint-ignore ban-types
  public clone<NE extends EventsType = {}>(cloneListeners = false) {
    const emitter = new MyExtendableEventEmitter<E & NE>();
    if (cloneListeners) {
      for (const [key, set] of (this as Any)._events_) {
        (emitter as Any)._events_.set(key, new Set([...set]));
      }
    }
    return emitter;
  }
}
```

![image](https://user-images.githubusercontent.com/35933830/157782320-e388e81e-71c9-4ccb-96dc-a8b1066ceeac.png)

That is the best you're going to get it

**Comment by ihack2712** [comment]
You can also make classes extandable if you prefer that, but that requires implementation on each class:

```ts
import { EventEmitter } from "https://deno.land/x/eventemitter@1.2.4/mod.ts";

// To make Deno lint less irritating.
// deno-lint-ignore no-explicit-any
type Any = any;

type Callback = (...args: Any[]) => Any | Promise<Any>;
type EventsType = { [key: string]: Callback } & { [key: number]: Callback };

// deno-lint-ignore ban-types
class MyEmitter1<E extends EventsType = {}> extends EventEmitter<
  {
    test1(a: number): unknown;
  } & E
> {
}

// deno-lint-ignore ban-types
class MyEmitter2<E extends EventsType = {}> extends MyEmitter1<
  {
    test2(b: string): unknown;
  } & E
> {
}
```

![image](https://user-images.githubusercontent.com/35933830/157782843-38655830-cc54-4401-af74-d14e3a8deaaf.png)

![image](https://user-images.githubusercontent.com/35933830/157782882-07178ec8-106e-4bc4-ab11-f8ac4835790d.png)

**Comment by shah** [comment]
Thanks for the elaboration @ihack2712 - and I'm intrigued about your new library, too. Let me know when it's ready and I'll put it through its paces as I use EventEmitter quite often in my codebases for event driven programming.
